name:                duration
version:             0.2.0.0
github:              "ryota-ka/duration"
license:             BSD3
author:              "Ryota Kameoka"
maintainer:          "kameoka.ryota@gmail.com"
copyright:           "2018 Ryota Kameoka"

extra-source-files:
- README.md

synopsis: A tiny compile-time time utility library inspired by zeit/ms
category: Time

description: A tiny compile-time time utility library inspired by zeit/ms

dependencies:
- base >= 4.7 && < 5
- parsec
- template-haskell
- time

library:
  source-dirs: src

tests:
  spec:
    main:                Spec.hs
    source-dirs:         spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - duration
    - hspec
  doctest:
    main:                Doctest.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - duration
    - doctest
